xivo/tests/test_xivo_helpers.py
xivo/xivo_helpers.py

the opening square bracket in the match group causes a warning.
/usr/lib/python3/dist-packages/xivo/xivo_helpers.py:12: FutureWarning: Possible nested set at position 1
find_asterisk_pattern_char = re.compile('[[NXZ!.]').search

extension helpers: fix warning during regex compilation

---

xivo/http_helpers.py
xivo/tests/test_http_helpers.py

Useful for debugging wazo-dird problems.

http_helpers: log response body for debug logs

---

xivo/http_helpers.py

Why:
* the params argument can not be an empty dict

http_helpers: fix traceback when logging empty response

---

xivo/http_helpers.py

reason: otherwise there are several content_type that can break the
code. An example to make wazo-ui compatible with this, would be:
```diff
-NOT_PRINTABLE_CONTENT_TYPES = ['application/octet-stream', 'application/pdf']
+NOT_PRINTABLE_CONTENT_TYPES = [
+    'application/octet-stream',
+    'application/pdf',
+    'text/html; charset=utf-8',
+    'text/css; charset=utf-8',
+    'font/woff2',
+    'image/svg+xml',
+    'application/javascript',
+]
```

http_helper: inverse printable_content_type logic

---

xivo/token_renewer.py

Why:
* When a non-HTTPError occurs, we don't have any information about the
actual problem.

token_renewer: add debug logs showing the exception

---

xivo/tenant_helpers.py
xivo/tests/test_tenant_helpers.py

reason: it will avoid to make request twice or more for the same request

tenant_helpers: add cache for visible_tenants

---

xivo/tenant_helpers.py
xivo/tests/test_tenant_helpers.py

reason: tenant check_against_token can be implemented by trying to list
this specific tenant. If user has access to see it, then it's because
it's part of his sub tenant. Moreover, by doing this way, it will
initialized cache with a value that will prevent a second call to
visible_tenants(tenant_uuid=<tenant-uuid-to-verify)

improve tenant cache to avoid duplicate requests

---

xivo/tenant_flask_helpers.py
xivo/tenant_helpers.py
xivo/tests/test_tenant_helpers.py

reason: used by cdr recording to be able to set tenant from
query string. To allow to download media directly by the browser
(without headers)

WAZO-2250 Pull request for extract-tenant-from-query

---

xivo/token_renewer.py

ConnectionError when wazo-auth is down is normal and should not trigger a
long traceback, even in debug mode
Probably not my best code ... any improvement is welcome :smiley:

token renewer: avoid to show traceback on known errors

---

xivo/asterisk/protocol_interface.py
xivo/asterisk/tests/test_protocol_interface.py

This lib is now used by call-logd to extract protocol and interface

asterisk proto: allow to have star code in interface

---

integration_tests/suite/test_service_discovery.py

reason: service_port() returns only port bound to ipv4. Some host can
resolve localhost to ipv6 address and docker doesn't necessarily bind
the same port number on ipv4 and ipv6

test: use explicit ipv4 addr to connect docker

---

debian/control

Why:
* python-consul package is not used (no Python 2 service needs Consul)
* python-consul package can't compile correctly (invalid syntax) with
Python 2

remove python-consul dependency

---

xivo/auth_verifier.py
xivo/tests/test_auth_verifier.py

reason: we don't want to return 404 if invalid token is provided because
it doesn't exist

verify_tenant: return 401 if no token

---

xivo/asterisk/protocol_interface.py
xivo/asterisk/tests/test_protocol_interface.py

why: because pjsip migration code has been removed and now, interface can
be PJSIP/abc

protocol_interface: accept pjsip interface

---

xivo/consul_helpers.py

Why:
* If ConsulException is raised and not caught, the service discovery
thread will crash, needing a service restart.

[WAZO-2526] consul helpers: catch ConsulException everywhere

---

xivo/auth_verifier.py
xivo/tests/test_auth_verifier.py

Why:
* Will be needed for a new method
Why:
* The logic is different when checking if access is allowed and when
checking if access can be added

Pull request for WAZO-2530-auth-allow-adding-negative-acl

---

integration_tests/Dockerfile-myservice
integration_tests/assets/docker-compose.yml
integration_tests/test-requirements.txt
requirements.txt

Why:
* Use the correct version of consul
* python-consul 0.7 is not compatible with consul 1.0.7
* We are using python-consul 1.1.0 in Wazo Platform

tests: update consul docker image

---

xivo/chain_map.py
xivo/config_helper.py
xivo/tests/test_chain_map.py
xivo/tests/test_config_helper.py

Why:
* So that lists can be appended from drop-in config files

config_helper: add config parser accumulating lists

---

integration_tests/suite/test_service_discovery.py

why: the name of project now include asset name

fix generated docker-compose project name

---

xivo/mallow/fields.py

why: original message is format string which is populated when calling
`make_error`. Overriding this method imply code change in all fields and
maintain the implementation in wazo side, which doesn't worth it.

mallow: hardcode original format string for error

---

xivo/http_helpers.py
xivo/tests/test_http_helpers.py

http_helpers: log request duration

---

README.md
debian/control
integration_tests/Dockerfile-myservice
integration_tests/Dockerfile-thread-exception
integration_tests/assets/docker-compose.yml
integration_tests/test-requirements.txt
requirements.txt
test-requirements.txt
tox.ini
xivo/tests/test_auth_verifier.py
xivo/tests/test_http_helpers.py
xivo/tests/test_tenant_helpers.py
zuul.yaml

Depends-On: https://github.com/wazo-platform/wazo-auth-client/pull/35
Depends-On: https://github.com/wazo-platform/wazo-lib-rest-client/pull/14
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/84

Update to use Python 3.9 on bullseye

---

xivo/rest_api_helpers.py

Why:
* The import error may come from a nested import

rest api helpers: log import error

---

integration_tests/suite/test_service_discovery.py

why: it's now the recommended way to use docker compose

use docker compose without hyphen command

---

xivo/auth_verifier.py
xivo/tenant_flask_helpers.py
xivo/tenant_helpers.py
xivo/tests/test_auth_verifier.py
xivo/tests/test_tenant_helpers.py
zuul.yaml

Remove one query to wazo-auth when `Wazo-Tenant` is provided
And the query sent is now a `HEAD /tokens` instead of `GET /tenants` which is a lot faster

WP-1476 improve authentication/tenant workflow

---

xivo/flask/auth_verifier.py
xivo/flask/headers.py
xivo/flask/tests/test_auth_verifier.py
xivo/tenant_flask_helpers.py
xivo/tenant_helpers.py
xivo/tests/test_tenant_flask_helpers.py
xivo/tests/test_tenant_helpers.py

why: will remove a query to wazo-auth when Wazo-Tenant is present

validate and share tenant_uuid from verify_token with autodetect

---

xivo/auth_verifier.py
xivo/http_exceptions.py

why: we are now verifying tenant and scope at the same time, so both can
trigger a 403

add tenant_uuid to Unauthorized exception

---

requirements.txt
xivo/mallow_helpers.py

This change uses the Bookworm version of marshmallow to reduce the scope of changes that are going to happen when doing the upgrade

Use marshmallow version 3.18.0 from Bookworm

---

xivo/auth_verifier.py
xivo/tests/test_auth_verifier.py

why: wazo-auth suffix was not consistant with other services and
documentation. Instead of create a breaking change, we will allow edit
and update for ACL for some time

auth_verifier: add reserved word 'edit' to 'update'

---

xivo/flask/auth_verifier.py

why:
- makes retrieving the required_acl easier from within the request context

add required_acl to flask's g object
